image:
  pillarbox:
    target_ratio: 1.33333333
    fill: "white"
  letterbox:
    target_ratio: 1.77777777
    fill: "black"
  windowbox:
    height_to_add: 0
    width_to_add: 0
    fill: "blur"
  color_filter:
    kernel: [1]
  rotate:
    angle: 0
  crop:
    rows: 0
    columns: 0
  scale:
    x: 1.0
    y: 1.0
  scale_uniform:
    ratio: 1.0
  scale_to_fit:
    height:
    width:
  blur:
    ksize: 20
    sigma: 10
video:
  screenshot:
    frame: 0
  adjust_speed:
    scale: 1.0
  adjust_duration:
    scale: 1.0
  crop_duration:
    start:
      hour: 0
      minute: 0
      second: 0.0
    end:
      hour: 0
      minute: 0
      second: 0.0
  adjust_frames:
    fps: 30
  rearrange_group:
    group_size: 20
  embed_descriptors:
    top: 100
